#!/usr/bin/env python3
import json
from pathlib import Path
from ledger_reader import read_combined_ledger


ROOT = Path(__file__).resolve().parents[2]


def require(text: str, needle: str, label: str) -> None:
    if needle not in text:
        raise SystemExit(f"SREV-261 failed: {label} missing {needle!r}")


schema = json.loads(
    (ROOT / "docs/plan/srev-261-dllhook-wow64-stub-comment-owner.schema.json").read_text()
)
if schema.get("$schema") != "http://json-schema.org/draft-07/schema#":
    raise SystemExit("SREV-261 failed: schema is not draft-07")
if schema.get("id") != "DLLHOOK_WOW64_STUB_COMMENT_OWNER":
    raise SystemExit("SREV-261 failed: wrong schema id")

contracts = "\n".join(schema["contracts"])
for term in [
    "SREV-247 owns the 13-byte",
    "stub byte layout intent",
    "does not change allocation generated bytes",
]:
    require(contracts, term, "schema")

dllhook = (ROOT / "Sandboxie/core/dll/dllhook.c").read_text()
srev_247 = (ROOT / "docs/plan/srev-247-dllhook-wow64-stub-publish-gate.md").read_text()
srev_247_check = (ROOT / "docs/plan/check-srev-247.py").read_text()
ledger = read_combined_ledger(ROOT)
ledger_fragment = (ROOT / "docs/plan/ledger/srev-261.md").read_text()

start = dllhook.index("_FX void Dll_FixWow64Syscall(void)")
end = dllhook.index("_FX ULONG_PTR  DLL_FindWow64Target", start)
func = dllhook[start:end]

for term in [
    "SREV-247 owns this 13-byte pre-Windows 10 WOW64 stub:",
    "and eax,0xFFFF; xor ecx,ecx; jmp [push target; ret].",
    "*(ULONG *)(_code + 0) = 0xFF25C933;",
    "*(ULONG *)(_code + 4) = 0x680000FF;",
    "*(ULONG *)(_code + 8) = X86SwitchTo64BitMode;",
    "*(UCHAR *)(_code + 12) = 0xc3;",
    "FlushInstructionCache(GetCurrentProcess(), _code, 13);",
    "__writefsdword(0xC0, (ULONG)_code);",
]:
    require(func, term, "Dll_FixWow64Syscall")

for term in [
    "source comment now points at this SREV",
    "source comment ownership of the generated byte sequence",
]:
    require(srev_247, term, "SREV-247 spec adjacency")

for term in [
    "SREV-247 owns this 13-byte pre-Windows 10 WOW64 stub:",
    "and eax,0xFFFF; xor ecx,ecx; jmp [push target; ret].",
    "13-byte pre-Windows 10 WOW64 transition stub",
]:
    require(srev_247_check, term, "SREV-247 checker adjacency")

for term in [
    "### SREV-261: DLL Hook WOW64 Stub Comment Owner",
    "DLLHOOK_WOW64_STUB_COMMENT_OWNER",
    "srev-261-dllhook-wow64-stub-comment-owner.schema.json",
    "Sandboxie/core/dll/dllhook.c",
    "Dll_FixWow64Syscall",
    "SREV-247",
]:
    require(ledger, term, "combined ledger")
    require(ledger_fragment, term, "ledger fragment")

print("SREV-261 source gate passed")
