#!/usr/bin/env python3
import json
from pathlib import Path
from ledger_reader import read_combined_ledger


ROOT = Path(__file__).resolve().parents[2]


def require(text: str, needle: str, label: str) -> None:
    if needle not in text:
        raise SystemExit(f"SREV-247 failed: {label} missing {needle!r}")


schema = json.loads(
    (ROOT / "docs/plan/srev-247-dllhook-wow64-stub-publish-gate.schema.json").read_text()
)
if schema.get("$schema") != "http://json-schema.org/draft-07/schema#":
    raise SystemExit("SREV-247 failed: schema is not draft-07")
if schema.get("id") != "DLLHOOK_WOW64_STUB_PUBLISH_GATE":
    raise SystemExit("SREV-247 failed: wrong schema id")

contracts = "\n".join(schema["contracts"])
for term in [
    "pre-Windows 10 WOW64 transition stub",
    "Dll_AllocCode128 may fail and must be gated",
    "generated stub is executable code and must be flushed before publication",
    "__writefsdword(0xC0) is the publication edge",
    "must not change the generated byte sequence",
]:
    require(contracts, term, "schema")

dllhook = (ROOT / "Sandboxie/core/dll/dllhook.c").read_text()
spec = (ROOT / "docs/plan/srev-247-dllhook-wow64-stub-publish-gate.md").read_text()
ledger = read_combined_ledger(ROOT)
ledger_fragment = (ROOT / "docs/plan/ledger/srev-247.md").read_text()

for term in schema["official_references"]:
    require(spec, term, "spec official reference")

func_start = dllhook.index("_FX void Dll_FixWow64Syscall(void)")
func_end = dllhook.index("_FX ULONG_PTR  DLL_FindWow64Target", func_start)
func = dllhook[func_start:func_end]

for term in [
    "if(Dll_CompartmentMode || SbieApi_QueryConfBool(NULL, L\"NoSysCallHooks\", FALSE))",
    "if (Dll_IsWow64) {",
    "if (Dll_Windows >= 10) {",
    "myAddress = (UCHAR *)VirtualAlloc(NULL, 0x100, MEM_COMMIT, PAGE_EXECUTE_READWRITE);",
    "else {\n            if (!_code) {",
    "ULONG X86SwitchTo64BitMode = __readfsdword(0xC0);",
    "_code = (UCHAR *)Dll_AllocCode128();",
    "if (! _code)\n                    return;",
    "SREV-247 owns this 13-byte pre-Windows 10 WOW64 stub:",
    "and eax,0xFFFF; xor ecx,ecx; jmp [push target; ret].",
    "*(ULONG *)(_code + 0) = 0xFF25C933;",
    "*(ULONG *)(_code + 4) = 0x680000FF;",
    "*(ULONG *)(_code + 8) = X86SwitchTo64BitMode;",
    "*(UCHAR *)(_code + 12) = 0xc3;",
    "FlushInstructionCache(GetCurrentProcess(), _code, 13);",
    "__writefsdword(0xC0, (ULONG)_code);",
]:
    require(func, term, "Dll_FixWow64Syscall source")

alloc_pos = func.index("_code = (UCHAR *)Dll_AllocCode128();")
gate_pos = func.index("if (! _code)\n                    return;", alloc_pos)
first_write_pos = func.index("*(ULONG *)(_code + 0) = 0xFF25C933;", alloc_pos)
flush_pos = func.index("FlushInstructionCache(GetCurrentProcess(), _code, 13);", first_write_pos)
publish_pos = func.index("__writefsdword(0xC0, (ULONG)_code);", flush_pos)

if not (alloc_pos < gate_pos < first_write_pos < flush_pos < publish_pos):
    raise SystemExit("SREV-247 failed: allocation/flush/publish order is wrong")

for term in [
    "allocation failure writes through `_code == NULL`",
    "freshly generated executable stub is published without an instruction",
    "gate allocation success",
    "FlushInstructionCache(stub, 13)",
    "13-byte pre-Windows 10 WOW64 transition stub",
    "Windows 10 path",
]:
    require(spec, term, "spec local contract")

for term in [
    "### SREV-247: DLL Hook WOW64 Stub Publish Gate",
    "DLLHOOK_WOW64_STUB_PUBLISH_GATE",
    "srev-247-dllhook-wow64-stub-publish-gate.schema.json",
    "Sandboxie/core/dll/dllhook.c",
    "Dll_FixWow64Syscall",
    "Dll_AllocCode128",
    "FlushInstructionCache",
    "__writefsdword",
]:
    require(ledger, term, "combined ledger")
    require(ledger_fragment, term, "ledger fragment")

print("SREV-247 source gate passed")
